development:
  adapter: sqlite3
  database: database.db

test:
  adapter: sqlite3
  database: database.db

production:
  adapter: postgresql
  database: my_personal_ea_database
  username: username
  password: password
  host: localhost
